export interface CountryCode {
  code: string // Code pays ISO (ex: "US", "FR")
  name: string // Nom du pays en anglais
  nameFr: string // Nom du pays en français
  dialCode: string // Indicatif téléphonique (ex: "+1", "+33")
  flag: string // Emoji du drapeau
}

export const countryCodes: CountryCode[] = [
  { code: "AF", name: "Afghanistan", nameFr: "Afghanistan", dialCode: "+93", flag: "🇦🇫" },
  { code: "ZA", name: "South Africa", nameFr: "Afrique du Sud", dialCode: "+27", flag: "🇿🇦" },
  { code: "AL", name: "Albania", nameFr: "Albanie", dialCode: "+355", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", nameFr: "Algérie", dialCode: "+213", flag: "🇩🇿" },
  { code: "DE", name: "Germany", nameFr: "Allemagne", dialCode: "+49", flag: "🇩🇪" },
  { code: "AD", name: "Andorra", nameFr: "Andorre", dialCode: "+376", flag: "🇦🇩" },
  { code: "AO", name: "Angola", nameFr: "Angola", dialCode: "+244", flag: "🇦🇴" },
  { code: "SA", name: "Saudi Arabia", nameFr: "Arabie Saoudite", dialCode: "+966", flag: "🇸🇦" },
  { code: "AR", name: "Argentina", nameFr: "Argentine", dialCode: "+54", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", nameFr: "Arménie", dialCode: "+374", flag: "🇦🇲" },
  { code: "AU", name: "Australia", nameFr: "Australie", dialCode: "+61", flag: "🇦🇺" },
  { code: "AT", name: "Austria", nameFr: "Autriche", dialCode: "+43", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", nameFr: "Azerbaïdjan", dialCode: "+994", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", nameFr: "Bahamas", dialCode: "+1-242", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", nameFr: "Bahreïn", dialCode: "+973", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", nameFr: "Bangladesh", dialCode: "+880", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", nameFr: "Barbade", dialCode: "+1-246", flag: "🇧🇧" },
  { code: "BE", name: "Belgium", nameFr: "Belgique", dialCode: "+32", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", nameFr: "Belize", dialCode: "+501", flag: "🇧🇿" },
  { code: "BJ", name: "Benin", nameFr: "Bénin", dialCode: "+229", flag: "🇧🇯" },
  { code: "BT", name: "Bhutan", nameFr: "Bhoutan", dialCode: "+975", flag: "🇧🇹" },
  { code: "BY", name: "Belarus", nameFr: "Biélorussie", dialCode: "+375", flag: "🇧🇾" },
  { code: "BO", name: "Bolivia", nameFr: "Bolivie", dialCode: "+591", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", nameFr: "Bosnie-Herzégovine", dialCode: "+387", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", nameFr: "Botswana", dialCode: "+267", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", nameFr: "Brésil", dialCode: "+55", flag: "🇧🇷" },
  { code: "BN", name: "Brunei", nameFr: "Brunei", dialCode: "+673", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", nameFr: "Bulgarie", dialCode: "+359", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", nameFr: "Burkina Faso", dialCode: "+226", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", nameFr: "Burundi", dialCode: "+257", flag: "🇧🇮" },
  { code: "KH", name: "Cambodia", nameFr: "Cambodge", dialCode: "+855", flag: "🇰🇭" },
  { code: "CM", name: "Cameroon", nameFr: "Cameroun", dialCode: "+237", flag: "🇨🇲" },
  { code: "CA", name: "Canada", nameFr: "Canada", dialCode: "+1", flag: "🇨🇦" },
  { code: "CV", name: "Cape Verde", nameFr: "Cap-Vert", dialCode: "+238", flag: "🇨🇻" },
  { code: "CL", name: "Chile", nameFr: "Chili", dialCode: "+56", flag: "🇨🇱" },
  { code: "CN", name: "China", nameFr: "Chine", dialCode: "+86", flag: "🇨🇳" },
  { code: "CY", name: "Cyprus", nameFr: "Chypre", dialCode: "+357", flag: "🇨🇾" },
  { code: "CO", name: "Colombia", nameFr: "Colombie", dialCode: "+57", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", nameFr: "Comores", dialCode: "+269", flag: "🇰🇲" },
  { code: "CG", name: "Congo", nameFr: "Congo", dialCode: "+242", flag: "🇨🇬" },
  { code: "CD", name: "DR Congo", nameFr: "RD Congo", dialCode: "+243", flag: "🇨🇩" },
  { code: "KR", name: "South Korea", nameFr: "Corée du Sud", dialCode: "+82", flag: "🇰🇷" },
  { code: "KP", name: "North Korea", nameFr: "Corée du Nord", dialCode: "+850", flag: "🇰🇵" },
  { code: "CR", name: "Costa Rica", nameFr: "Costa Rica", dialCode: "+506", flag: "🇨🇷" },
  { code: "CI", name: "Ivory Coast", nameFr: "Côte d'Ivoire", dialCode: "+225", flag: "🇨🇮" },
  { code: "HR", name: "Croatia", nameFr: "Croatie", dialCode: "+385", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", nameFr: "Cuba", dialCode: "+53", flag: "🇨🇺" },
  { code: "DK", name: "Denmark", nameFr: "Danemark", dialCode: "+45", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", nameFr: "Djibouti", dialCode: "+253", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", nameFr: "Dominique", dialCode: "+1-767", flag: "🇩🇲" },
  { code: "EG", name: "Egypt", nameFr: "Égypte", dialCode: "+20", flag: "🇪🇬" },
  { code: "AE", name: "United Arab Emirates", nameFr: "Émirats Arabes Unis", dialCode: "+971", flag: "🇦🇪" },
  { code: "EC", name: "Ecuador", nameFr: "Équateur", dialCode: "+593", flag: "🇪🇨" },
  { code: "ER", name: "Eritrea", nameFr: "Érythrée", dialCode: "+291", flag: "🇪🇷" },
  { code: "ES", name: "Spain", nameFr: "Espagne", dialCode: "+34", flag: "🇪🇸" },
  { code: "EE", name: "Estonia", nameFr: "Estonie", dialCode: "+372", flag: "🇪🇪" },
  { code: "US", name: "United States", nameFr: "États-Unis", dialCode: "+1", flag: "🇺🇸" },
  { code: "ET", name: "Ethiopia", nameFr: "Éthiopie", dialCode: "+251", flag: "🇪🇹" },
  { code: "FJ", name: "Fiji", nameFr: "Fidji", dialCode: "+679", flag: "🇫🇯" },
  { code: "FI", name: "Finland", nameFr: "Finlande", dialCode: "+358", flag: "🇫🇮" },
  { code: "FR", name: "France", nameFr: "France", dialCode: "+33", flag: "🇫🇷" },
  { code: "GA", name: "Gabon", nameFr: "Gabon", dialCode: "+241", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", nameFr: "Gambie", dialCode: "+220", flag: "🇬🇲" },
  { code: "GE", name: "Georgia", nameFr: "Géorgie", dialCode: "+995", flag: "🇬🇪" },
  { code: "GH", name: "Ghana", nameFr: "Ghana", dialCode: "+233", flag: "🇬🇭" },
  { code: "GR", name: "Greece", nameFr: "Grèce", dialCode: "+30", flag: "🇬🇷" },
  { code: "GD", name: "Grenada", nameFr: "Grenade", dialCode: "+1-473", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", nameFr: "Guatemala", dialCode: "+502", flag: "🇬🇹" },
  { code: "GN", name: "Guinea", nameFr: "Guinée", dialCode: "+224", flag: "🇬🇳" },
  { code: "GQ", name: "Equatorial Guinea", nameFr: "Guinée Équatoriale", dialCode: "+240", flag: "🇬🇶" },
  { code: "GW", name: "Guinea-Bissau", nameFr: "Guinée-Bissau", dialCode: "+245", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", nameFr: "Guyana", dialCode: "+592", flag: "🇬🇾" },
  { code: "HT", name: "Haiti", nameFr: "Haïti", dialCode: "+509", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", nameFr: "Honduras", dialCode: "+504", flag: "🇭🇳" },
  { code: "HU", name: "Hungary", nameFr: "Hongrie", dialCode: "+36", flag: "🇭🇺" },
  { code: "IN", name: "India", nameFr: "Inde", dialCode: "+91", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", nameFr: "Indonésie", dialCode: "+62", flag: "🇮🇩" },
  { code: "IQ", name: "Iraq", nameFr: "Irak", dialCode: "+964", flag: "🇮🇶" },
  { code: "IR", name: "Iran", nameFr: "Iran", dialCode: "+98", flag: "🇮🇷" },
  { code: "IE", name: "Ireland", nameFr: "Irlande", dialCode: "+353", flag: "🇮🇪" },
  { code: "IS", name: "Iceland", nameFr: "Islande", dialCode: "+354", flag: "🇮🇸" },
  { code: "IL", name: "Israel", nameFr: "Israël", dialCode: "+972", flag: "🇮🇱" },
  { code: "IT", name: "Italy", nameFr: "Italie", dialCode: "+39", flag: "🇮🇹" },
  { code: "JM", name: "Jamaica", nameFr: "Jamaïque", dialCode: "+1-876", flag: "🇯🇲" },
  { code: "JP", name: "Japan", nameFr: "Japon", dialCode: "+81", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", nameFr: "Jordanie", dialCode: "+962", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", nameFr: "Kazakhstan", dialCode: "+7", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", nameFr: "Kenya", dialCode: "+254", flag: "🇰🇪" },
  { code: "KG", name: "Kyrgyzstan", nameFr: "Kirghizistan", dialCode: "+996", flag: "🇰🇬" },
  { code: "KI", name: "Kiribati", nameFr: "Kiribati", dialCode: "+686", flag: "🇰🇮" },
  { code: "KW", name: "Kuwait", nameFr: "Koweït", dialCode: "+965", flag: "🇰🇼" },
  { code: "LA", name: "Laos", nameFr: "Laos", dialCode: "+856", flag: "🇱🇦" },
  { code: "LS", name: "Lesotho", nameFr: "Lesotho", dialCode: "+266", flag: "🇱🇸" },
  { code: "LV", name: "Latvia", nameFr: "Lettonie", dialCode: "+371", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", nameFr: "Liban", dialCode: "+961", flag: "🇱🇧" },
  { code: "LR", name: "Liberia", nameFr: "Libéria", dialCode: "+231", flag: "🇱🇷" },
  { code: "LY", name: "Libya", nameFr: "Libye", dialCode: "+218", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", nameFr: "Liechtenstein", dialCode: "+423", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", nameFr: "Lituanie", dialCode: "+370", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", nameFr: "Luxembourg", dialCode: "+352", flag: "🇱🇺" },
  { code: "MK", name: "North Macedonia", nameFr: "Macédoine du Nord", dialCode: "+389", flag: "🇲🇰" },
  { code: "MG", name: "Madagascar", nameFr: "Madagascar", dialCode: "+261", flag: "🇲🇬" },
  { code: "MY", name: "Malaysia", nameFr: "Malaisie", dialCode: "+60", flag: "🇲🇾" },
  { code: "MW", name: "Malawi", nameFr: "Malawi", dialCode: "+265", flag: "🇲🇼" },
  { code: "MV", name: "Maldives", nameFr: "Maldives", dialCode: "+960", flag: "🇲🇻" },
  { code: "ML", name: "Mali", nameFr: "Mali", dialCode: "+223", flag: "🇲🇱" },
  { code: "MT", name: "Malta", nameFr: "Malte", dialCode: "+356", flag: "🇲🇹" },
  { code: "MA", name: "Morocco", nameFr: "Maroc", dialCode: "+212", flag: "🇲🇦" },
  { code: "MU", name: "Mauritius", nameFr: "Maurice", dialCode: "+230", flag: "🇲🇺" },
  { code: "MR", name: "Mauritania", nameFr: "Mauritanie", dialCode: "+222", flag: "🇲🇷" },
  { code: "MX", name: "Mexico", nameFr: "Mexique", dialCode: "+52", flag: "🇲🇽" },
  { code: "FM", name: "Micronesia", nameFr: "Micronésie", dialCode: "+691", flag: "🇫🇲" },
  { code: "MD", name: "Moldova", nameFr: "Moldavie", dialCode: "+373", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", nameFr: "Monaco", dialCode: "+377", flag: "🇲🇨" },
  { code: "MN", name: "Mongolia", nameFr: "Mongolie", dialCode: "+976", flag: "🇲🇳" },
  { code: "ME", name: "Montenegro", nameFr: "Monténégro", dialCode: "+382", flag: "🇲🇪" },
  { code: "MZ", name: "Mozambique", nameFr: "Mozambique", dialCode: "+258", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar", nameFr: "Myanmar", dialCode: "+95", flag: "🇲🇲" },
  { code: "NA", name: "Namibia", nameFr: "Namibie", dialCode: "+264", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", nameFr: "Nauru", dialCode: "+674", flag: "🇳🇷" },
  { code: "NP", name: "Nepal", nameFr: "Népal", dialCode: "+977", flag: "🇳🇵" },
  { code: "NI", name: "Nicaragua", nameFr: "Nicaragua", dialCode: "+505", flag: "🇳🇮" },
  { code: "NE", name: "Niger", nameFr: "Niger", dialCode: "+227", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", nameFr: "Nigeria", dialCode: "+234", flag: "🇳🇬" },
  { code: "NO", name: "Norway", nameFr: "Norvège", dialCode: "+47", flag: "🇳🇴" },
  { code: "NZ", name: "New Zealand", nameFr: "Nouvelle-Zélande", dialCode: "+64", flag: "🇳🇿" },
  { code: "OM", name: "Oman", nameFr: "Oman", dialCode: "+968", flag: "🇴🇲" },
  { code: "UG", name: "Uganda", nameFr: "Ouganda", dialCode: "+256", flag: "🇺🇬" },
  { code: "UZ", name: "Uzbekistan", nameFr: "Ouzbékistan", dialCode: "+998", flag: "🇺🇿" },
  { code: "PK", name: "Pakistan", nameFr: "Pakistan", dialCode: "+92", flag: "🇵🇰" },
  { code: "PW", name: "Palau", nameFr: "Palaos", dialCode: "+680", flag: "🇵🇼" },
  { code: "PA", name: "Panama", nameFr: "Panama", dialCode: "+507", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", nameFr: "Papouasie-Nouvelle-Guinée", dialCode: "+675", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", nameFr: "Paraguay", dialCode: "+595", flag: "🇵🇾" },
  { code: "NL", name: "Netherlands", nameFr: "Pays-Bas", dialCode: "+31", flag: "🇳🇱" },
  { code: "PE", name: "Peru", nameFr: "Pérou", dialCode: "+51", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", nameFr: "Philippines", dialCode: "+63", flag: "🇵🇭" },
  { code: "PL", name: "Poland", nameFr: "Pologne", dialCode: "+48", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", nameFr: "Portugal", dialCode: "+351", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", nameFr: "Qatar", dialCode: "+974", flag: "🇶🇦" },
  { code: "DO", name: "Dominican Republic", nameFr: "République Dominicaine", dialCode: "+1-809", flag: "🇩🇴" },
  { code: "CZ", name: "Czech Republic", nameFr: "République Tchèque", dialCode: "+420", flag: "🇨🇿" },
  { code: "RO", name: "Romania", nameFr: "Roumanie", dialCode: "+40", flag: "🇷🇴" },
  { code: "GB", name: "United Kingdom", nameFr: "Royaume-Uni", dialCode: "+44", flag: "🇬🇧" },
  { code: "RU", name: "Russia", nameFr: "Russie", dialCode: "+7", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", nameFr: "Rwanda", dialCode: "+250", flag: "🇷🇼" },
  { code: "KN", name: "Saint Kitts and Nevis", nameFr: "Saint-Kitts-et-Nevis", dialCode: "+1-869", flag: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", nameFr: "Sainte-Lucie", dialCode: "+1-758", flag: "🇱🇨" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameFr: "Saint-Vincent-et-les-Grenadines", dialCode: "+1-784", flag: "🇻🇨" },
  { code: "SB", name: "Solomon Islands", nameFr: "Îles Salomon", dialCode: "+677", flag: "🇸🇧" },
  { code: "WS", name: "Samoa", nameFr: "Samoa", dialCode: "+685", flag: "🇼🇸" },
  { code: "SM", name: "San Marino", nameFr: "Saint-Marin", dialCode: "+378", flag: "🇸🇲" },
  { code: "ST", name: "Sao Tome and Principe", nameFr: "Sao Tomé-et-Principe", dialCode: "+239", flag: "🇸🇹" },
  { code: "SN", name: "Senegal", nameFr: "Sénégal", dialCode: "+221", flag: "🇸🇳" },
  { code: "RS", name: "Serbia", nameFr: "Serbie", dialCode: "+381", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", nameFr: "Seychelles", dialCode: "+248", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", nameFr: "Sierra Leone", dialCode: "+232", flag: "🇸🇱" },
  { code: "SG", name: "Singapore", nameFr: "Singapour", dialCode: "+65", flag: "🇸🇬" },
  { code: "SK", name: "Slovakia", nameFr: "Slovaquie", dialCode: "+421", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", nameFr: "Slovénie", dialCode: "+386", flag: "🇸🇮" },
  { code: "SO", name: "Somalia", nameFr: "Somalie", dialCode: "+252", flag: "🇸🇴" },
  { code: "SD", name: "Sudan", nameFr: "Soudan", dialCode: "+249", flag: "🇸🇩" },
  { code: "SS", name: "South Sudan", nameFr: "Soudan du Sud", dialCode: "+211", flag: "🇸🇸" },
  { code: "LK", name: "Sri Lanka", nameFr: "Sri Lanka", dialCode: "+94", flag: "🇱🇰" },
  { code: "SE", name: "Sweden", nameFr: "Suède", dialCode: "+46", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", nameFr: "Suisse", dialCode: "+41", flag: "🇨🇭" },
  { code: "SR", name: "Suriname", nameFr: "Suriname", dialCode: "+597", flag: "🇸🇷" },
  { code: "SZ", name: "Eswatini", nameFr: "Eswatini", dialCode: "+268", flag: "🇸🇿" },
  { code: "SY", name: "Syria", nameFr: "Syrie", dialCode: "+963", flag: "🇸🇾" },
  { code: "TJ", name: "Tajikistan", nameFr: "Tadjikistan", dialCode: "+992", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzania", nameFr: "Tanzanie", dialCode: "+255", flag: "🇹🇿" },
  { code: "TD", name: "Chad", nameFr: "Tchad", dialCode: "+235", flag: "🇹🇩" },
  { code: "TH", name: "Thailand", nameFr: "Thaïlande", dialCode: "+66", flag: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", nameFr: "Timor-Leste", dialCode: "+670", flag: "🇹🇱" },
  { code: "TG", name: "Togo", nameFr: "Togo", dialCode: "+228", flag: "🇹🇬" },
  { code: "TO", name: "Tonga", nameFr: "Tonga", dialCode: "+676", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", nameFr: "Trinité-et-Tobago", dialCode: "+1-868", flag: "🇹🇹" },
  { code: "TN", name: "Tunisia", nameFr: "Tunisie", dialCode: "+216", flag: "🇹🇳" },
  { code: "TM", name: "Turkmenistan", nameFr: "Turkménistan", dialCode: "+993", flag: "🇹🇲" },
  { code: "TR", name: "Turkey", nameFr: "Turquie", dialCode: "+90", flag: "🇹🇷" },
  { code: "TV", name: "Tuvalu", nameFr: "Tuvalu", dialCode: "+688", flag: "🇹🇻" },
  { code: "UA", name: "Ukraine", nameFr: "Ukraine", dialCode: "+380", flag: "🇺🇦" },
  { code: "UY", name: "Uruguay", nameFr: "Uruguay", dialCode: "+598", flag: "🇺🇾" },
  { code: "VU", name: "Vanuatu", nameFr: "Vanuatu", dialCode: "+678", flag: "🇻🇺" },
  { code: "VE", name: "Venezuela", nameFr: "Venezuela", dialCode: "+58", flag: "🇻🇪" },
  { code: "VN", name: "Vietnam", nameFr: "Vietnam", dialCode: "+84", flag: "🇻🇳" },
  { code: "YE", name: "Yemen", nameFr: "Yémen", dialCode: "+967", flag: "🇾🇪" },
  { code: "ZM", name: "Zambia", nameFr: "Zambie", dialCode: "+260", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", nameFr: "Zimbabwe", dialCode: "+263", flag: "🇿🇼" },
]

export function getCountryName(country: CountryCode, language: "fr" | "en"): string {
  return language === "fr" ? country.nameFr : country.name
}


export function getSortedCountryCodes(language: "fr" | "en"): CountryCode[] {
  return [...countryCodes].sort((a, b) => {
    const nameA = getCountryName(a, language)
    const nameB = getCountryName(b, language)
    return nameA.localeCompare(nameB, language)
  })
}
