name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Deploy to VPS (Dev)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/cabinetdab
            git pull origin develop
            
            # Créer le fichier .env.development avec les secrets GitHub
            cat > .env.development << 'ENV_EOF'
DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}
NODE_ENV=${{ secrets.DEV_NODE_ENV }}
PORT=${{ secrets.DEV_PORT }}
ENV_EOF
            
            npm install
            npm run build
            pm2 restart cabinetdab-dev || pm2 start npm --name "cabinetdab-dev" -- run dev
