name: Deploy to VPS

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Determine environment
        id: env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "env_prefix=PROD" >> $GITHUB_OUTPUT
          else
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "env_prefix=DEV" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          ENV_PREFIX: ${{ steps.env.outputs.env_prefix }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: ENV_PREFIX
          script: |
            cd /var/www/cabinetdab
            git pull origin master
            
            # Créer le fichier .env avec les secrets GitHub
            cat > .env.production << 'ENV_EOF'
DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}
NODE_ENV=${{ secrets.PROD_NODE_ENV }}
PORT=${{ secrets.PROD_PORT }}
ENV_EOF
            
            npm install
            npm run build
            pm2 restart cabinetdab || pm2 start npm --name "cabinetdab" -- start
